### ISSUE TITLE
Location not working properly. See Discrimination Around Housing and Housing Assistance and Subsidized Housing with zip code 96813 where orgs from Maui and Kauai show up (STG)

### ISSUE THREAD

**Issue by KellyeDC** [LSCOIT/LegalNavigator#1026]
Location not working properly. See Discrimination Around Housing and Housing Assistance and Subsidized Housing with zip code 96813 where orgs from Maui and Kauai show up (STG)

Reported by Alex Forger 1/10/2020

**Comment by ozholob** [comment]
@KellyeDC Hello! 
We've fixed that on the development environment. (You can see that on dev there are 7 organizations only instead of 15 on stage)
![image](https://user-images.githubusercontent.com/55988406/72260572-d132b680-361b-11ea-95c4-9dd42b60f64e.png)
![image](https://user-images.githubusercontent.com/55988406/72260633-f3c4cf80-361b-11ea-94a0-8b0e991c69b3.png)

**Comment by KellyeDC** [comment]
@grawdon Ready for review in DEV.

**Comment by grawdon** [comment]
@KellyeDC I tested it for the scenario outlined and Maui and Kaui resources no longer showing up.
