### ISSUE TITLE
when connecting  GUIDs in A2J dropdown menu do not seem to be consistent 

### ISSUE THREAD

**Issue by KellyeDC** [LSCOIT/LegalNavigator#1107]
when connecting  GUIDs in A2J. The options that show in the dropdown menu do not seem to be consistent with our most recent spreadsheets. I also noticed that the titles with those odd extensions (see screenshot) that we talked about in the past are still showing up.

**Comment by KellyeDC** [comment]
![GUID dropdown](https://user-images.githubusercontent.com/59450227/81356721-dd95c000-909f-11ea-91d4-288af60384af.png)

**Comment by svasylenko** [comment]
Doubling is due to 2 records in DB: 1 as of Feb 11 and the second is for Feb 27.

First one:
![image](https://user-images.githubusercontent.com/46557859/81690830-88252e80-9464-11ea-95f3-ec419d1da625.png)

second one (seems to be correct as has much more content):

![image](https://user-images.githubusercontent.com/46557859/81690865-96734a80-9464-11ea-975c-823f1cc6899c.png)


I will delete first one from DB to stop doublings.

**Comment by svasylenko** [comment]
Completed. @KellyeDC please review and we could close the ticket.

**Comment by yevhenobertas** [comment]
@KellyeDC Done. Please review
