### ISSUE TITLE
As a Portal User, I need to access learning resources (videos, articles, etc.) about legal term or subject (such as child custody).

### ISSUE THREAD

**Issue by aroubin** [LSCOIT/LegalNavigator#14]
_From @czdiana2321 on May 3, 2018 1:3_

#25 Create UI for topic & resource page
#26 Create UI for individual topics page
#27 Create control for homepage to list topics
#28 Create backend service
#48 Create UI for Sub-topic page

_Copied from original issue: Microsoft/Access2Justice#14_

**Comment by aroubin** [comment]
_From @yfzwinnie on June 5, 2018 23:40_

Code review with Alaa and Andrew completed. Moving to Resolve.

**Comment by aroubin** [comment]
_From @amitabhm21 on June 13, 2018 19:30_

This works end to end now. Closing the user story

**Comment by svasylenko** [comment]
UI for topics and resources:
![image](https://user-images.githubusercontent.com/46557859/51607828-768ddf80-1f1e-11e9-9595-406349b3fbbe.png)

UI for subtopics:
![image](https://user-images.githubusercontent.com/46557859/51607858-8b6a7300-1f1e-11e9-91a6-09ed8453d995.png)

#27 and #28 since both work - Verified.

UI for individual topic:
![image](https://user-images.githubusercontent.com/46557859/51607950-c7053d00-1f1e-11e9-88ef-4ffa87712fc1.png)
