### ISSUE TITLE
Personalized/secured browsing of site

### ISSUE THREAD

**Issue by svasylenko** [LSCOIT/LegalNavigator#816]
Security alert: Personalized surfing on the site is not secured at all - all links are direct and could be sniffed.

Steps to reproduce: log in, find something in Guided Assistant search. Copy link and past to any other browser.
![image](https://user-images.githubusercontent.com/46557859/51617992-0be89e00-1f36-11e9-9ebe-f4c97b496a10.png)

**Comment by alaatadmori** [comment]
@svasylenko this is not a bug. The Guided Assistant is a public resource and doesn't require logging in.

**Comment by svasylenko** [comment]
@alaatadmori Alaa, I agree that it should not require login but at the same time public doesn't mean everyone is able to see what I am personally looking for there. I.e. either it should be done via POST not GET or some tokenization should be implemented.

**Comment by alaatadmori** [comment]
@svasylenko I see what you mean. However, if the resource is public it should remain public after you sign in. Think of it as the "Help" page here in GitHub, you could be reading one of the help topics, then you decide to login, GitHub will sign you in and take you back to the same help page you were reading, still using GET request.

Also, please note that this URL design of resource/id combination was intentional as it allows for easy sharing and linking to various resources and guided assistant flows from various places in the portal.

**Comment by aroubin** [comment]
There is no issue here - curated experience is a public resource just like any other resource on the site, such as topic page or organization page etc..

**Comment by svasylenko** [comment]
Agreed that this is not a bug but expected behavior. Closed.
