### ISSUE TITLE
Inactive Web Pages

### ISSUE THREAD

**Issue by KellyeDC-zz** [LSCOIT/LegalNavigator#911]
It looks like links to webpages aren’t active in the “learn mores.”

Issue submitted by Stacey Marz (AK)

**Comment by breeglej** [comment]
@KellyeDC - I think this is saying that webpages are not actually live links in LN.  Tried to attach screanshot showing the problem on one page.  This needs to be high priority.  As an end user, I need to be able to click on all links and be directed to the site in another window.  Perhaps this gets fixed with that story.

![Capture](https://user-images.githubusercontent.com/42586446/56048066-b6da4e00-5d14-11e9-8cec-8bc8f5ca580b.JPG)

**Comment by KellyeDC-zz** [comment]
Once all related items are fixed, I will close all defects referenced.

**Comment by svasylenko** [comment]
this to be fixed on stage only since fixing on dev requires much more time and no real need for that.

**Comment by svasylenko** [comment]
Done in Dev - @KellyeDC  please suggest moving to Stage

**Comment by KellyeDC-zz** [comment]
@svasylenko Requires PO approval.  Assign to me for testing and I will pass it on to @grawdon

**Comment by KellyeDC-zz** [comment]
It is working fine in the DEV environment. Ready for PO review.

**Comment by grawdon** [comment]
All of the external links to sites and forms I tested worked.
